### ISSUE TITLE
Add boolean decorator which defaults to true

### ISSUE THREAD

**Issue by gtnx** [davidbonnet/realue#22]
With current `boolean` implementation, default value is `false`. It'd be nice to control this.

**Comment by davidbonnet** [comment]
Defaulting a boolean to `false` is a natural default, akin `[]` for an array, `{}` for an object, and so on.

Realue’s decorator design guideline is to be modular and to set behavior from props as much as possible.

Should there be a different default value wanted, the `defaultValue` decorator can fulfill that:

```js
const BooleanComponent = compose(
  defaultValue,
  boolean,
)(({ value }) => <span>{value ? 'True' : 'False'}</span>)

// Sets `defaultValue` to `true` and renders <span>True</span>
<BooleanComponent defaultValue />
```
