### ISSUE TITLE
Add a HOC to provide a onChange without name required

### ISSUE THREAD

**Issue by gtnx** [davidbonnet/realue#23]
We may use realue awesome HOCs on top of third parties components which have different various `onChange` signatures.

The simplest case i can think is `onChange(value)`. For instance, this is the case for [react-datetime](https://github.com/YouCanBookMe/react-datetime) or [react-bootstrap-typeahead](https://github.com/ericgio/react-bootstrap-typeahead). In that case, we add the same hoc:

```js
const withRealueOnChange = withHandlers({
  onChange: ({ onChange, name }) => value => onChange(value, name),
})
```

Several ideas:
- Move `onChange` signature to `onChange(value, payload)`. 
- `property` and `item` hoc provide on additional props `onChangeSimple`
- Handle the case where name is undefined and use by the default the one from props

What do you think?

**Comment by davidbonnet** [comment]
Great suggestion!

Indeed, we need an adapter that includes the `name` as second argument, akin `fromEvent`:
https://github.com/davidbonnet/realue/blob/e2cd5401266c1daff820fa0ca593238c3da1afa9/src/dom.js#L24-L33)

Could be called `fromValue`:
```js
export const fromValue = memoize(path => {
  return branch(
    hasProp('onChange'),
    withHandlers({
      onChange: ({ onChange, name }) => value =>
        onChange(path == null ? value : get(value, path), name),
    }),
  )
})
```

**Comment by gtnx** [comment]
Sure we can do that but I still don't understand why the `name` is required in the `onChange` prop provided by `object` hoc.

In other words, what would be the cost of turning this code:

https://github.com/davidbonnet/realue/blob/master/src/objects.js#L28-L38

into

```
  withHandlers({
    property: ({ value, onChangeProperty }) => (
      name,
      key = name,
    ) => ({
      value: value[name],
      key,
      name,
      onChange: (value, payload) => onChangeProperty(value, name, payload),
    }),
  }),
```

**Comment by davidbonnet** [comment]
@gtnx: The cost is similar to assigning a function expression to a prop: it updates at each render.
