### ISSUE TITLE
withBounds debounces very slowly if we are making the window smaller, it works fine if we make the window bigger

### ISSUE THREAD

**Issue by thibautrey** [davidbonnet/realue#47]
```
const MyComp = compose(
   withBounds(),
   logProps(["width"])
)
```

Displays width fairly fast if expanding the window, displays almost pixel per pixel if we shrink the window

**Comment by thibautrey** [comment]
```
const MyComp = compose(
   withBounds(),
   logProps(["width"])
)
```

Displays width fairly fast if expanding the window, displays almost pixel per pixel if we shrink the window

**Comment by davidbonnet** [comment]
Probably due to some CSS. Demo shows that it works fine.
